/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package microfinancemanagement;

import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Atel Dot Net
 */
public class AdmissionForm extends javax.swing.JFrame {

    private BufferedImage chosen_picture;
    private String filename=null;
    private byte[]personimage=null;
    int select=0;
    int Member_Id;
    /**
     * Creates new form AdmissionForm
     */
    public AdmissionForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Occupation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MemberName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FatherorHusbandName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MotherName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Presentaddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PermanentAddress = new javax.swing.JTextField();
        labelGender = new javax.swing.JLabel();
        Nationality = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        MobileNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        NationalId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Religious = new javax.swing.JTextField();
        lblimage = new javax.swing.JLabel();
        InsertImageButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Gender = new javax.swing.JComboBox<>();
        RegisterButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ADMISSION FORM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 30, 360, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1380, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("OCCUPATION :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 520, 240, 50);

        Occupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OccupationActionPerformed(evt);
            }
        });
        getContentPane().add(Occupation);
        Occupation.setBounds(340, 530, 310, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("NATIONALITY :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(720, 330, 140, 50);

        MemberName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberNameActionPerformed(evt);
            }
        });
        getContentPane().add(MemberName);
        MemberName.setBounds(340, 170, 310, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("FATHER /HUSBAND  NAME :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 280, 260, 50);
        getContentPane().add(FatherorHusbandName);
        FatherorHusbandName.setBounds(340, 290, 310, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("MOTHER  NAME :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 340, 240, 50);
        getContentPane().add(MotherName);
        MotherName.setBounds(340, 350, 310, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("PRESENT ADDRESS :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 400, 220, 50);
        getContentPane().add(Presentaddress);
        Presentaddress.setBounds(340, 410, 310, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("PERMANENT ADDRESS :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 460, 240, 50);

        PermanentAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermanentAddressActionPerformed(evt);
            }
        });
        getContentPane().add(PermanentAddress);
        PermanentAddress.setBounds(340, 470, 310, 30);

        labelGender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelGender.setText("GENDER :");
        getContentPane().add(labelGender);
        labelGender.setBounds(70, 220, 160, 50);

        Nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationalityActionPerformed(evt);
            }
        });
        getContentPane().add(Nationality);
        Nationality.setBounds(870, 340, 310, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("MOBILE NO :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(720, 150, 120, 50);

        MobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileNoActionPerformed(evt);
            }
        });
        getContentPane().add(MobileNo);
        MobileNo.setBounds(870, 160, 310, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("NATIONAL ID:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(720, 210, 140, 50);

        NationalId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationalIdActionPerformed(evt);
            }
        });
        getContentPane().add(NationalId);
        NationalId.setBounds(870, 220, 310, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("RELIGIOUS :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(720, 270, 140, 50);

        Religious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReligiousActionPerformed(evt);
            }
        });
        getContentPane().add(Religious);
        Religious.setBounds(870, 280, 310, 30);

        lblimage.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblimage.setText("         Load Image");
        lblimage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(lblimage);
        lblimage.setBounds(870, 390, 270, 190);

        InsertImageButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        InsertImageButton.setText("INSERT IMAGE");
        InsertImageButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        InsertImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertImageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InsertImageButton);
        InsertImageButton.setBounds(870, 590, 180, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("MEMBER NAME :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 160, 160, 50);

        Gender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHERS" }));
        Gender.setBorder(null);
        getContentPane().add(Gender);
        Gender.setBounds(340, 230, 310, 26);

        RegisterButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RegisterButton.setText("REGISTER");
        RegisterButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterButton);
        RegisterButton.setBounds(500, 590, 150, 50);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(50, 120, 1180, 10);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(1240, 120, 100, 560);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(50, 670, 1180, 10);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel5);
        jPanel5.setBounds(30, 120, 10, 560);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel6);
        jPanel6.setBounds(680, 140, 10, 520);

        setSize(new java.awt.Dimension(1397, 765));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MemberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberNameActionPerformed

    private void OccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OccupationActionPerformed

    private void PermanentAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermanentAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PermanentAddressActionPerformed

    private void NationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NationalityActionPerformed

    private void MobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileNoActionPerformed

    private void NationalIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationalIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NationalIdActionPerformed

    private void ReligiousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReligiousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReligiousActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
             

            String sql = "Insert into AdmissionForm"
                    +"(MemberName, FatherorHusbandName, MotherName, PresentAddress, Permanentaddress, Occupation, MobileNo, NationalId, Religious, Nationality,Gender, MemberImage)"
                    +"values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
           /* String sql2 = "Insert into DEPOSIT_TOTAL"
                    +"(MemberId,Total_Amount)"
                    +"values(?, ?)";
               
            PreparedStatement pst2 = con.prepareStatement(sql2);
            
            */
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, MemberName.getText());
            pst.setString(2, FatherorHusbandName.getText());
            pst.setString(3, MotherName.getText());
            pst.setString(4, Presentaddress.getText());
            pst.setString(5, PermanentAddress.getText());
            pst.setString(6, Occupation.getText());
            pst.setString(7, MobileNo.getText());
            pst.setString(8, NationalId.getText());
            pst.setString(9, Religious.getText());
            pst.setString(10, Nationality.getText());
            pst.setString(11, Gender.getSelectedItem().toString());

            pst.setBytes(12,  personimage);

           
            
        
            pst.executeUpdate();
        
               JOptionPane.showMessageDialog(null, "Successfully Registered");
           
              
               
                MemberName.setText("");
                FatherorHusbandName.setText("");
                MotherName.setText("");
                
                Presentaddress.setText("");
                PermanentAddress.setText("");
                Occupation.setText("");
                
                MobileNo.setText("");
                NationalId.setText("");
                Religious.setText("");
                
                Nationality.setText("");
                lblimage.setText("");
            
                
                con.close();
                
                CREATE_DEPOSIT();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void InsertImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertImageButtonActionPerformed
        // TODO add your handling code here:
     
       JFileChooser chooser=new JFileChooser();
       chooser.showOpenDialog(null);
       File f=chooser.getSelectedFile();
       filename=f.getAbsolutePath();
       ImageIcon imageicon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), 100));
       lblimage.setIcon(imageicon);
       try
       {
           File image=new File(filename);
           FileInputStream fis=new FileInputStream(image);
           
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) 
            {
              bos.write(buf, 0, readNum);
             // System.out.println("read " + readNum + " bytes,");
            }
            
            personimage = bos.toByteArray();
           
       }catch(Exception e)
       {
           
       }
       

        
    }//GEN-LAST:event_InsertImageButtonActionPerformed

    public void CREATE_DEPOSIT()
    {
        
        FIND_ID();
          try
        {
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
             

           
            
            String sql2 = "Insert into DEPOSIT_TOTAL"
                    +"(MemberId,Total_Amount)"
                    +"values(?, ?)";
               
            PreparedStatement pst2 = con.prepareStatement(sql2);

            pst2.setInt(1, Member_Id);
            
            pst2.setFloat(2, 0);
          
           
            pst2.executeUpdate();
        
               JOptionPane.showMessageDialog(null, "Successfully Registered");
           
                con.close();
                
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    
    public void FIND_ID()
    {
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;selectMethod=cursor", "sa", "123456");


            Statement statement = connection.createStatement();
            
            ResultSet resultSet = statement
                    .executeQuery("SELECT MemberId FROM AdmissionForm");
            
            while (resultSet.next()) {
                
               Member_Id =resultSet.getInt("MemberId");
            }
           
            JOptionPane.showMessageDialog(null, "YOUR MEMBER ID - "+Member_Id);
            
           connection.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmissionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmissionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmissionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmissionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmissionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FatherorHusbandName;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JButton InsertImageButton;
    private javax.swing.JTextField MemberName;
    private javax.swing.JTextField MobileNo;
    private javax.swing.JTextField MotherName;
    private javax.swing.JTextField NationalId;
    private javax.swing.JTextField Nationality;
    private javax.swing.JTextField Occupation;
    private javax.swing.JTextField PermanentAddress;
    private javax.swing.JTextField Presentaddress;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField Religious;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel lblimage;
    // End of variables declaration//GEN-END:variables
}
