/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package microfinancemanagement;

import java.awt.Image;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Atel Dot Net
 */
public class Deposit extends javax.swing.JFrame {

    DefaultListModel defaultListModel=new DefaultListModel();
    int MemberID;
    String memberid;
    String MemberName;
    String Table_Member_name;
    boolean MouseExit=false;
    boolean DataExist=false;
    public String Admin;
    StringBuffer strBuffer = new StringBuffer();
    
     Vector<String> DATA1 = new Vector<String>(); 
       Vector<String> DATA2 = new Vector<String>();
       Vector<String> DATA3 = new Vector<String>();
       float Table_SUM=0;
       String MEMBER_TABLE_NAME;
    /**
     * Creates new form Deposit
     */
    public Deposit() {
        initComponents();
        
       jScrollPane2.setVisible(false);
       jScrollPane2.setBounds(0,0,0,0);
       this.bindData();
    }

       
 private ArrayList getStars()
{
    ArrayList stars=new ArrayList();
    
    try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        Connection connection = DriverManager.getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;selectMethod=cursor", "sa", "123456");


            Statement statement = connection.createStatement();
            ResultSet resultSet = statement
                    .executeQuery("SELECT MemberId, MemberName FROM AdmissionForm");
            
            
            while (resultSet.next()) {
                
                MemberID=resultSet.getInt("MemberId");
                MemberName=resultSet.getString("MemberName");
                stars.add(MemberID+"   "+MemberName);
            }
            
           connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    
   
return stars;
}
 
 
 
   private void bindData(){
        

getStars().stream().forEach((star) -> {
defaultListModel.addElement(star);
});

jList1.setModel(defaultListModel);
jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
}
   
   private void searchFilter(String searchTerm)
{
DefaultListModel filteredItems=new DefaultListModel();
ArrayList stars=getStars();
stars.stream().forEach((star) -> {
String starName=star.toString().toLowerCase();
if (starName.contains(searchTerm.toLowerCase())) {
filteredItems.addElement(star);
}
});
defaultListModel=filteredItems;
jList1.setModel(defaultListModel);

}
   
   public void setAdminName(String Admin)
   {
       this.Admin=Admin;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MemberNameText = new javax.swing.JLabel();
        MemberIdText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DepositDate = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();
        DepositAmount = new javax.swing.JTextField();
        AddDeposit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SearchMember = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PRINT_BUTTON = new javax.swing.JButton();
        TotalDeposit = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(null);

        jList1.setBackground(new java.awt.Color(0, 51, 255));
        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jList1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jList1MouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(880, 230, 460, 0);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("DEPOSIT MONEY");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(520, 20, 340, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1370, 0);

        MemberNameText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MemberNameText.setForeground(new java.awt.Color(153, 0, 153));
        jPanel1.add(MemberNameText);
        MemberNameText.setBounds(40, 230, 590, 50);

        MemberIdText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MemberIdText.setForeground(new java.awt.Color(153, 0, 153));
        jPanel1.add(MemberIdText);
        MemberIdText.setBounds(40, 180, 590, 50);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER AMOUNT :");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 140, 160, 40);

        DepositDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED,
            (java.awt.Color)null,
            (java.awt.Color)null,
            (java.awt.Color)null,
            (java.awt.Color)null));
    DepositDate.setCalendarPreferredSize(new java.awt.Dimension(418, 231));
    jPanel4.add(DepositDate);
    DepositDate.setBounds(190, 70, 320, 40);

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("SELECT DATE      :");
    jPanel4.add(jLabel3);
    jLabel3.setBounds(20, 70, 160, 40);

    DepositAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    DepositAmount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jPanel4.add(DepositAmount);
    DepositAmount.setBounds(190, 140, 320, 40);

    AddDeposit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    AddDeposit.setText("ADD");
    AddDeposit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    AddDeposit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            AddDepositActionPerformed(evt);
        }
    });
    jPanel4.add(AddDeposit);
    AddDeposit.setBounds(270, 210, 120, 60);

    jPanel3.add(jPanel4);
    jPanel4.setBounds(30, 30, 530, 330);

    jPanel1.add(jPanel3);
    jPanel3.setBounds(40, 290, 590, 390);

    jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "SERIAL", "DATE", "PAID", "RESIDUE"
        }
    ));
    jTable1.setRowHeight(25);
    jScrollPane1.setViewportView(jTable1);

    jPanel1.add(jScrollPane1);
    jScrollPane1.setBounds(650, 290, 690, 390);

    SearchMember.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    SearchMember.setForeground(new java.awt.Color(0, 51, 255));
    SearchMember.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    SearchMember.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            SearchMemberMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            SearchMemberMouseExited(evt);
        }
    });
    SearchMember.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            SearchMemberKeyReleased(evt);
        }
    });
    jPanel1.add(SearchMember);
    SearchMember.setBounds(900, 250, 440, 40);

    jPanel5.setBackground(new java.awt.Color(0, 51, 204));
    jPanel5.setLayout(null);

    jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("DEPOSIT");
    jPanel5.add(jLabel4);
    jLabel4.setBounds(570, 10, 340, 70);

    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microfinancemanagement/deposit5.png"))); // NOI18N
    jPanel5.add(jLabel8);
    jLabel8.setBounds(270, 0, 90, 90);

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microfinancemanagement/deposit3.png"))); // NOI18N
    jPanel5.add(jLabel9);
    jLabel9.setBounds(1060, 0, 110, 90);

    PRINT_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microfinancemanagement/print64.png"))); // NOI18N
    PRINT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            PRINT_BUTTONActionPerformed(evt);
        }
    });
    jPanel5.add(PRINT_BUTTON);
    PRINT_BUTTON.setBounds(1240, 0, 130, 90);

    jPanel1.add(jPanel5);
    jPanel5.setBounds(0, 0, 1370, 90);

    TotalDeposit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    TotalDeposit.setForeground(new java.awt.Color(102, 0, 102));
    jPanel1.add(TotalDeposit);
    TotalDeposit.setBounds(910, 150, 430, 70);

    jPanel6.setBackground(new java.awt.Color(0, 51, 204));
    jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jPanel6.setLayout(null);

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microfinancemanagement/search.png"))); // NOI18N
    jPanel6.add(jLabel7);
    jLabel7.setBounds(200, 0, 50, 40);

    jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("SEARCH MEMBER");
    jPanel6.add(jLabel6);
    jLabel6.setBounds(10, 0, 170, 40);

    jPanel1.add(jPanel6);
    jPanel6.setBounds(650, 250, 250, 40);

    jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jPanel7.setLayout(null);

    Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microfinancemanagement/profile1.png"))); // NOI18N
    jPanel7.add(Image);
    Image.setBounds(0, 0, 250, 160);

    jPanel1.add(jPanel7);
    jPanel7.setBounds(650, 90, 250, 160);

    getContentPane().add(jPanel1);
    jPanel1.setBounds(0, 0, 1370, 730);

    setSize(new java.awt.Dimension(1381, 767));
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchMemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMemberMouseEntered
        // TODO add your handling code here:
        jScrollPane2.setVisible(true);
        jScrollPane2.setBounds(900, 285, 440, 400);
    }//GEN-LAST:event_SearchMemberMouseEntered

    private void SearchMemberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMemberMouseExited
        // TODO add your handling code here:
        if(MouseExit==true)
        {
             jScrollPane2.setVisible(false);
             jScrollPane2.setBounds(900, 285, 0, 0);
        }
       
    }//GEN-LAST:event_SearchMemberMouseExited

    private void jList1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseEntered
        // TODO add your handling code here:
        jScrollPane2.setVisible(true);
        jScrollPane2.setBounds(900, 285, 440, 400);
    }//GEN-LAST:event_jList1MouseEntered

    private void jList1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseExited
        // TODO add your handling code here:
        MouseExit=true;
        jScrollPane2.setVisible(false);
        jScrollPane2.setBounds(900, 285, 0, 0);
    }//GEN-LAST:event_jList1MouseExited

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
       String selct=jList1.getSelectedValue().toString();
     
        Vector<Character> s1 = new Vector<Character>(); 
        Vector<Character> s2 = new Vector<Character>(); 
        // Use add() method to add elements into the Vector 
       // vec_tor.add(10); 

       int i=0;
       char wt;
       
       for(i=0; i<selct.length(); i++)
       {
            wt=selct.charAt(i);
            // char c='a';
            if(Character.isWhitespace(wt)==false)
            {
                  s1.add(selct.charAt(i));                
            } 
            else if(Character.isWhitespace(wt)==true)
            {
               // s1[i]=selct.charAt(i);
                i=i+3;
                break;
                
            } 
           // s1[i]=selct.charAt(i);
       }
       
       int l=0;
       for(int k=i+l; k<selct.length(); k++)
       {
           s2.add(selct.charAt(k));
           l++;
       }
     /*  for(int m=0; m<30; m++)
       {
           System.out.println(s1[m]+"  "+s2[m]);
       }
       */
     
   //  Character[] array1 = s1.toArray(new Character[s1.size()]);
    // Character[] array2 = s2.toArray(new Character[s2.size()]);
    int size1=s1.size();
    int size2=s2.size();
    
    char ss1[]=new char[size1];
    char ss2[]=new char[size2];
    
    
    for(i=0; i<size1; i++)
    {
        ss1[i]=s1.get(i);
    }
    
    for(i=0; i<size2; i++)
    {
        ss2[i]=s2.get(i);
    }
     
      //System.out.println("hellow");
      String st1=new String(ss1);
      memberid=st1;
   //  String bt=st1;
      String st2=new String(ss2);
    
      //System.out.println(st1);
      //System.out.println(st2);
      
     // System.out.println(st1.length());
     // System.out.println(st2.length());

       Integer result1 = Integer.valueOf(st1);
       MemberID=result1;
     //  System.out.println(result1);
      
      //  JOptionPane.showMessageDialog(rootPane,jList1.getSelectedValue(), "Selected Member", JOptionPane.INFORMATION_MESSAGE);
       
            
        MemberIdText.setText("MEMBER ID : "+st1);
        MemberNameText.setText("MEMEBR NAME : "+st2);
        MEMBER_TABLE_NAME=st2;
      getData(st1);
      
        jScrollPane2.setVisible(false);
        jScrollPane2.setBounds(900, 285, 0, 0);
        
        Fetch_Image();
        DePosit_Total();
     
    }//GEN-LAST:event_jList1MouseClicked

    private void SearchMemberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchMemberKeyReleased
        // TODO add your handling code here:
        searchFilter(SearchMember.getText());
    }//GEN-LAST:event_SearchMemberKeyReleased

    private void AddDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDepositActionPerformed
        // TODO add your handling code here:
        String amount=DepositAmount.getText().toString();
        
        if(amount.equals(""))
        {
            JOptionPane.showMessageDialog(null, "PLEASE ENTER AMOUNT");
        }
        else
        {
            
        
      try
        {
            
            float D_Amount=Float.parseFloat(amount);
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

            String sql = "Insert into DEPOSIT "
            +"(MemberId, Amount, PayementDay, EntryBy)"
            +"values(?, ?, ?, ?)";
            
            
           String sql2 = "Update DEPOSIT_TOTAL set Total_Amount = Total_Amount+"+D_Amount+" WHERE MemberId="+memberid;

            
            PreparedStatement pst = con.prepareStatement(sql);
            
            PreparedStatement pst2 = con.prepareStatement(sql2);
            
            String date=DepositDate.getText();
          
            pst.setString(1, memberid);
            pst.setFloat(2, D_Amount);
            pst.setString(3, DepositDate.getText());
            pst.setString(4, Admin);
            
            //////// MEMBER ID MAYBE INTEGER   ; THREAD
          //  pst2.setString(1, memberid);

          //  pst2.setFloat(1, D_Amount);

            
          //  System.out.println(Admin);
            
            pst.executeUpdate();
            pst2.executeUpdate();

            JOptionPane.showMessageDialog(null, "Successfully Entered Deposit");

            DepositAmount.setText("");
           
            DePosit_Total();
            con.close();
            getData(memberid);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_AddDepositActionPerformed

    private void PRINT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRINT_BUTTONActionPerformed
        // TODO add your handling code here:
         strBuffer.delete(0, strBuffer.length());
        strBuffer.append("<table style=\"width:100%\">\n"
                + "  <tr>\n"
                + "    <th>MICROFINANCE MANAGEMENT SYSTEM</th>\n"
                + "  </tr>\n"
                + "  \n"
                + "   <tr>\n"
                + "    <th>MODHUBAG DHAKA</th>\n"
                + "  </tr>\n"
                + "  \n"
                + "   <tr>\n"
                + "    <th>CONTACT : 01521407602</th>\n"
                + "  </tr>\n"
                + "    <th>Email : tanvirhasan.tanshen2019@gmail.com</th>\n"
                + "  </tr>\n"
                + "    <th>MEMBER NAME "+MEMBER_TABLE_NAME+"</th>\n"
                + "  </tr>\n"
                + "  \n"
                + "<tr></tr><tr></tr></table>");

        strBuffer.append("\n<table border = \"1\" cellpadding = \"5\" cellspacing = \"5\" style=\"width:100%; border: 1px solid black;\">\n"
                + "  <tr>\n"
                + "     <td>NO</td> \n"
                + "     <td>DATE</td>\n"
                + "     <td>AMOUNT</td>\n"
                + "    \n"
                + "  </tr>");

      
        int ln=DATA1.size();
        
        for(int i=0; i<ln; i++)
        {
             strBuffer.append(" <tr>\n"
                    + "    <td>" +i+ "</td>\n"
                    + "    <td>" + DATA1.elementAt(i)+ "</td>\n"
                    + "    <td>" + DATA2.elementAt(i)+ "</td>\n"
                    + "  </tr>");
        }
        
        
        strBuffer.append("</table>");

        strBuffer.append("<table style=\"width:100%\">\n"
                + "  <tr>\n"
                + "     <td align=\"right\">TOTAL AMOUNT : " +Table_SUM + "</td>\n"
                + "  </tr>\n"
                + "\n"
                + "</table>");

        strBuffer.append("\n\n<table style=\"width:100%\">\n"
                + "  <tr>\n"
                + "  <tr>\n"
                + "    <th>WELCOME FOR JOIN MICROFINANCE COMPANY </th>\n"
                + "   </tr>\n"
                + "  </tr>\n"
                + " \n"
                + "</table>");
        
        
        PrintData obj=new PrintData();
        obj.PrintString(strBuffer.toString());
        obj.setVisible(true);
       
    }//GEN-LAST:event_PRINT_BUTTONActionPerformed

    
     
    public void getData(String id)
    {
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection connection = DriverManager.getConnection(
                     "jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;selectMethod=cursor", "sa", "123456");


            Statement statement = connection.createStatement();
            String sql="SELECT Amount,PayementDay,EntryBy  FROM DEPOSIT WHERE MemberId="+id;
            
            ResultSet resultSet = statement
                    .executeQuery(sql);
            
             
           String[] columnNames = {"Serial", "AMOUNT","DATE","ENTRY BY"};
           DefaultTableModel model = new DefaultTableModel();
           model.setColumnIdentifiers(columnNames);
          
           jTable1.setModel(model);
            
           
            int i=1;
        
              
            Table_SUM=0;
            while (resultSet.next()) {
               
              
               String EntryBy =resultSet.getString("EntryBy");
               String date =resultSet.getString("PayementDay");

               float Amount= resultSet.getFloat("Amount");
               Table_SUM=Table_SUM+Amount;
                       
               model.addRow(new Object[]{i, Amount, date, EntryBy});
               i++;
               
               DATA1.add(date);
               DATA2.add(""+Amount);
            
            }
          
            
            connection.close();
                
        } catch (Exception e) {
            e.printStackTrace();
        }
         
    }
    
   public void Fetch_Image()
   {
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;selectMethod=cursor", "sa", "123456");


            Statement statement = connection.createStatement();
            String sql="SELECT MemberImage FROM AdmissionForm WHERE MemberId="+MemberID;
            //System.out.println(sql);
            ResultSet resultSet = statement
                    .executeQuery(sql);
        
           
            while (resultSet.next()) {
        
               
               InputStream in = resultSet.getBinaryStream("MemberImage");
               Image image = ImageIO.read(in);
               Image newimg = image.getScaledInstance(250, 160,  java.awt.Image.SCALE_SMOOTH);
               ImageIcon icon=new ImageIcon(newimg);

                Image.setIcon(icon);
                Image.revalidate();
                Image.revalidate();
                

                  
            }
         //   System.out.println("ResulsetCmplete");
            connection.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
  
   }
   
   public void DePosit_Total()
   {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;selectMethod=cursor", "sa", "123456");


            Statement statement = connection.createStatement();
            ResultSet resultSet = statement
                    .executeQuery("SELECT Total_Amount FROM DEPOSIT_TOTAL WHERE MemberId="+MemberID);
            
            /////////////////////
         //   System.out.println(MemberId);
            
            float total=0;
            while (resultSet.next()) {
                
               // Float amnt=resultSet.getFloat("Amount");
               // total =total+amnt;
                total=resultSet.getFloat("Total_Amount");
                
            }
            
            TotalDeposit.setText("TOTAL DEPOSITED :"+total);
        }catch(Exception e)
        {
            
        }
          
       
       
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDeposit;
    private javax.swing.JTextField DepositAmount;
    private datechooser.beans.DateChooserCombo DepositDate;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel MemberIdText;
    private javax.swing.JLabel MemberNameText;
    private javax.swing.JButton PRINT_BUTTON;
    private javax.swing.JTextField SearchMember;
    private javax.swing.JLabel TotalDeposit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
