/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package microfinancemanagement;

import java.awt.Image;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Atel Dot Net
 */
public class PayeMentShare extends javax.swing.JFrame {

    int BorrowerId, LenderId;
    public Connection connection;
    float Amount;
    String StartingDate;
    String Admin;
    /**
     * Creates new form PayeMentShare
     */
    public PayeMentShare() {
        initComponents();
        
    }
   
  public void setMemberID(int LId, int MemberId, String StartinDate, String Admin)
    {
        this.BorrowerId=MemberId;
        this.LenderId=LId;
        this.StartingDate=StartinDate;
        this.Admin=Admin;
        System.out.println("PAYEMENT SHARE :"+StartingDate);
        FirstMember();
        SecondMember();
     
         
       
    }
  
  public void  FirstMember()
  {
      try {
          
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;selectMethod=cursor", "sa", "123456");


            Statement statement = connection.createStatement();
            String sql="SELECT * FROM AdmissionForm WHERE MemberId="+LenderId;
            //System.out.println(sql);
            ResultSet resultSet = statement
                    .executeQuery(sql);
            
     
           
            while (resultSet.next()) {
                
            
                
                BmemberName.setText(resultSet.getString("MemberName"));
                Bphone.setText(resultSet.getString("MobileNo"));
                Bnid.setText(resultSet.getString("NationalId"));
                BID.setText(resultSet.getString("MemberId"));
              
                
               InputStream in = resultSet.getBinaryStream("MemberImage");
               Image image = ImageIO.read(in);
               Image newimg = image.getScaledInstance(190, 150,  java.awt.Image.SCALE_SMOOTH);
               ImageIcon icon=new ImageIcon(newimg);

          
                BorrowerImage.setIcon(icon);
                BorrowerImage.revalidate();
                BorrowerImage.revalidate();
                

                  
            }
            connection.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
  
  }
  
  
  public void SecondMember()
  {
      try {
          
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;selectMethod=cursor", "sa", "123456");


            Statement statement = connection.createStatement();
            String sql="SELECT * FROM AdmissionForm WHERE MemberId="+BorrowerId;
            //System.out.println(sql);
            ResultSet resultSet = statement
                    .executeQuery(sql);
            
     
           
            while (resultSet.next()) {
                
            
                
                Lname.setText(resultSet.getString("MemberName"));
                Lphone.setText(resultSet.getString("MobileNo"));
                Lnid.setText(resultSet.getString("NationalId"));
                Lid.setText(resultSet.getString("MemberId"));
              
                
               InputStream in = resultSet.getBinaryStream("MemberImage");
               Image image = ImageIO.read(in);
               Image newimg = image.getScaledInstance(200, 150,  java.awt.Image.SCALE_SMOOTH);
               ImageIcon icon=new ImageIcon(newimg);

          
                LenderImage.setIcon(icon);
                LenderImage.revalidate();
                LenderImage.revalidate();
                

                  
            }
            connection.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
  
  }
  
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        BorrowerImage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bphone = new javax.swing.JTextField();
        BID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BmemberName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Bnid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        LenderImage = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Lphone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Lid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Lname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Lnid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AmountText = new javax.swing.JTextField();
        TransferButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 124, 213));
        jPanel1.setLayout(null);

        jPanel4.setLayout(null);

        BorrowerImage.setText("                        IMAGE");
        jPanel4.add(BorrowerImage);
        BorrowerImage.setBounds(0, 0, 190, 150);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(220, 20, 190, 150);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PHONE NUMBER :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 520, 170, 40);

        Bphone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bphone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Bphone);
        Bphone.setBounds(180, 520, 300, 40);

        BID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(BID);
        BID.setBounds(180, 250, 300, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MEMBER NAME   :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 340, 160, 40);

        BmemberName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BmemberName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(BmemberName);
        BmemberName.setBounds(180, 340, 300, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NATIONAL ID     :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 430, 160, 40);

        Bnid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bnid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Bnid);
        Bnid.setBounds(180, 430, 300, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MEMBER ID         :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 250, 160, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 730);

        jPanel2.setBackground(new java.awt.Color(102, 124, 213));
        jPanel2.setLayout(null);

        jPanel5.setLayout(null);

        LenderImage.setText("                           IMAGE");
        jPanel5.add(LenderImage);
        LenderImage.setBounds(0, 0, 200, 150);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(220, 20, 200, 150);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PHONE NUMBER :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 510, 170, 40);

        Lphone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lphone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(Lphone);
        Lphone.setBounds(180, 510, 300, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MEMBER ID         :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 250, 160, 40);

        Lid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(Lid);
        Lid.setBounds(180, 250, 300, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MEMBER NAME   :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 340, 160, 40);

        Lname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(Lname);
        Lname.setBounds(180, 340, 300, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NATIONAL ID      :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 430, 170, 40);

        Lnid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lnid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(Lnid);
        Lnid.setBounds(180, 430, 300, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(870, 0, 500, 730);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MEMBER ID         :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 250, 160, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NATIONAL ID   :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 400, 150, 40);

        jPanel6.setBackground(new java.awt.Color(51, 186, 84));
        jPanel6.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PAYEMENT SHARE");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(20, 10, 340, 80);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(500, 0, 370, 100);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setText("ENTER AMOUNT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(530, 330, 310, 60);

        AmountText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(AmountText);
        AmountText.setBounds(540, 430, 290, 40);

        TransferButton.setBackground(new java.awt.Color(51, 153, 0));
        TransferButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TransferButton.setForeground(new java.awt.Color(255, 255, 255));
        TransferButton.setText("TRANSFER");
        TransferButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TransferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TransferButton);
        TransferButton.setBounds(600, 510, 150, 60);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microfinancemanagement/sign-out-option.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(610, 140, 150, 150);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microfinancemanagement/money-bag.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(770, 160, 80, 100);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microfinancemanagement/cash_64.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(520, 190, 70, 70);

        setSize(new java.awt.Dimension(1381, 769));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TransferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferButtonActionPerformed
        // TODO add your handling code here:
        String amount=AmountText.getText().toString();
        if(amount.equals(""))
        {
           JOptionPane.showMessageDialog(null, "ENTER AMOUNT FIRST");
           
        }
        else
        {
             Amount=Float.parseFloat(amount);
            
             try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection connection = DriverManager.getConnection(
                     "jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;selectMethod=cursor", "sa", "123456");


            Statement statement = connection.createStatement();
            String sql="SELECT Total_Amount FROM DEPOSIT_TOTAL WHERE MemberId="+LenderId;
            
            ResultSet resultSet = statement
                    .executeQuery(sql);
            
             
        
              
            float Total=0;
            
            while (resultSet.next()) {
               
          
               Total =resultSet.getFloat("Total_Amount");
              
             
            }
          
            if(Total>=Amount)
            {
                PayementShare_Table();
                LENDER_DEPOSIT_TOTAL();
                BORROWER_DEPOSIT();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "INSUFFICIENT BALANCE");
            }
            connection.close();
                
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        }
        
        
        
    }//GEN-LAST:event_TransferButtonActionPerformed

    public void PayementShare_Table()
    {
         try
        {
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
             

            String sql = "Insert into PAYEMENTSHARE"
                    +"(BorrowerId, LenderId, Amount, ShareDate)"
                    +"values(?, ?, ?, ?)";
            
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setInt(1, BorrowerId);
            pst.setInt(2, LenderId);
            pst.setFloat(3, Amount);
            pst.setString(4, StartingDate);
           
           
            
        
            pst.executeUpdate();
        
              // JOptionPane.showMessageDialog(null, "Successfully Registered");
           
              con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
      
    }
    
    public void LENDER_DEPOSIT_TOTAL()
    {
        
       try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);

           
           // PreparedStatement pst1 = con.prepareStatement(sql1);
            String sql = "Update DEPOSIT_TOTAL set Total_Amount=Total_Amount - ? WHERE MemberId="+LenderId;
            PreparedStatement pst = con.prepareStatement(sql);
          //  PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setFloat(1, Amount);
           
          
          //  ResultSet rs = pst.executeQuery();
            pst.executeUpdate();

            con.close();

    
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }  

    }
    
    public void BORROWER_DEPOSIT()
    {
          try
        {
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=MicroFinanceManagement;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
             

            String sql = "Insert into DEPOSIT"
                    +"(MemberId, Amount, PayementDay, EntryBy)"
                    +"values(?, ?, ?, ?)";
            
            String sql2 = "Update DEPOSIT_TOTAL set Total_Amount=Total_Amount + ? WHERE MemberId="+BorrowerId;

            PreparedStatement pst = con.prepareStatement(sql);
           
            PreparedStatement pst2 = con.prepareStatement(sql2);
            
            pst.setInt(1, BorrowerId);
            pst.setFloat(2, Amount);
            pst.setString(3, StartingDate);
            pst.setString(4, Admin);
            
            
           pst2.setFloat(1, Amount);

           
           
            
        
            pst.executeUpdate();
            pst2.executeUpdate();

            JOptionPane.showMessageDialog(null, "Successfully TRANSFERED BALANCE");
            dispose();
           
              con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
      
    }
    /**
     * @param args the command line arguments
     */
    
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayeMentShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayeMentShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayeMentShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayeMentShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayeMentShare().setVisible(true);
            }
        });
    
        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountText;
    private javax.swing.JTextField BID;
    private javax.swing.JTextField BmemberName;
    private javax.swing.JTextField Bnid;
    private javax.swing.JLabel BorrowerImage;
    private javax.swing.JTextField Bphone;
    private javax.swing.JLabel LenderImage;
    private javax.swing.JTextField Lid;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField Lnid;
    private javax.swing.JTextField Lphone;
    private javax.swing.JButton TransferButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
